-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 16:53:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cuadros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuadros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuadros` DEFAULT CHARACTER SET utf8 ;
USE `cuadros` ;

-- -----------------------------------------------------
-- Table `cuadros`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadros`.`comprador` (
  `idcomprador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idcomprador`),
  UNIQUE INDEX `idcomprador_UNIQUE` (`idcomprador` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuadros`.`cuadros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuadros`.`cuadros` (
  `idcuadros` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `compradorId` INT NOT NULL,
  PRIMARY KEY (`idcuadros`),
  UNIQUE INDEX `idcuadros_UNIQUE` (`idcuadros` ASC) ,
  UNIQUE INDEX `compradorId_UNIQUE` (`compradorId` ASC) ,
  CONSTRAINT `fk_cuadros_comprador`
    FOREIGN KEY (`compradorId`)
    REFERENCES `cuadros`.`comprador` (`idcomprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
