-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 16:15:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica3` DEFAULT CHARACTER SET utf8 ;
USE `optica3` ;

-- -----------------------------------------------------
-- Table `optica3`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica3`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT(10) NOT NULL,
  `piso` INT(10) NOT NULL,
  `puerta` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigoPostal` INT(20) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT(20) NOT NULL,
  `fax` INT(50) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `idproveedor_UNIQUE` (`idproveedor` ASC) ,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica3`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica3`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempleado`),
  UNIQUE INDEX `idempleado_UNIQUE` (`idempleado` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica3`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica3`.`gafas` (
  `idgafas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacionLente1` FLOAT NOT NULL,
  `graduacionLente2` FLOAT NOT NULL,
  `colorMontura` VARCHAR(45) NOT NULL,
  `tipoMontura` VARCHAR(45) NOT NULL,
  `coloLente1` VARCHAR(45) NOT NULL,
  `colorLente2` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `empleado_id` INT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`idgafas`),
  UNIQUE INDEX `idgafas_UNIQUE` (`idgafas` ASC) ,
  UNIQUE INDEX `proveedor_id_UNIQUE` (`proveedor_id` ASC) ,
  UNIQUE INDEX `empleado_id_UNIQUE` (`empleado_id` ASC) ,
  CONSTRAINT `fk_gafas_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `optica3`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gafas_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `optica3`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica3`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica3`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT(50) NOT NULL,
  `fecha` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `recomendacionCliente` INT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) ,
  UNIQUE INDEX `recomendacionCliente_UNIQUE` (`recomendacionCliente` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
