-- MySQL Script generated by MySQL Workbench
-- Tue Jul  7 14:59:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RedSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RedSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RedSocial` DEFAULT CHARACTER SET utf8 ;
USE `RedSocial` ;

-- -----------------------------------------------------
-- Table `RedSocial`.`nombre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`nombre` (
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `idNombre` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) ,
  PRIMARY KEY (`idNombre`),
  UNIQUE INDEX `idNombre_UNIQUE` (`idNombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedSocial`.`fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedSocial`.`fotografias` (
  `idFotografia` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  `nombre_id` INT NOT NULL,
  PRIMARY KEY (`idFotografia`),
  UNIQUE INDEX `idfotografias_UNIQUE` (`idFotografia` ASC) ,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) ,
  INDEX `fk_fotografias_nombre_idx` (`nombre_id` ASC) ,
  CONSTRAINT `fk_fotografias_nombre`
    FOREIGN KEY (`nombre_id`)
    REFERENCES `RedSocial`.`nombre` (`idNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
