-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 19:04:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueling` DEFAULT CHARACTER SET utf8 ;
USE `vueling` ;

-- -----------------------------------------------------
-- Table `vueling`.`Aviones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Aviones` (
  `idAviones` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAviones`),
  UNIQUE INDEX `idAviones_UNIQUE` (`idAviones` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`Asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueling`.`Asientos` (
  `idAsientos` INT NOT NULL AUTO_INCREMENT,
  `avion_id` INT NOT NULL,
  PRIMARY KEY (`idAsientos`),
  UNIQUE INDEX `idAsientos_UNIQUE` (`idAsientos` ASC) ,
  INDEX `fk_Asientos_Aviones_idx` (`avion_id` ASC) ,
  CONSTRAINT `fk_Asientos_Aviones`
    FOREIGN KEY (`avion_id`)
    REFERENCES `vueling`.`Aviones` (`idAviones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
